exports.Say = function Say() {
	console.log('Welcome to RCG node server');
	console.log('          _           _              _        ');
	console.log('        /         /            /       ');
	console.log('       /         /            /        ');
	console.log('      / /      / /         / / _    ');
	console.log('     / / / _  / / /       / / //_/    ');
	console.log('    / / /_/ / / / / /   _   / / / ______  ');
	console.log('   / / /__/ / / / /    /_/  / / / /_____ ');
	console.log('  / / /_____/ / / /          / / /  /____ / ');
	console.log(' / / /    / / /________  / / /_____/ / /  ');
	console.log('/ / /    / / /_________/ / /______/ /   ');
	console.log('/_/    _//____________//___________/    ');
	console.log();
	console.log();
	console.log('         \\');
	console.log(' \\      (o>');
	console.log(' (o>     // ');
	console.log('_(()_____V_/_____');
	console.log('||      ||');
	console.log('        ||');
};
